/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
	Auth: {
		region: 'us-east-1',
		userPoolId: 'us-east-1_VzpYkxRyA',
		userPoolWebClientId: 'jbf8mvvgmda4jp2bg6bep2deq',
		identityPoolId: 'us-east-1:03b1660b-b030-420d-8b66-34e1f3a07c3d',
		
	},
	Storage: {
		AWSS3: {
			bucket: 'filestoragestack-s3bucket64cb25af-15izsmtk02agi',
			region: 'us-east-1',
		},
	},
	aws_project_region: 'us-east-1',
	aws_appsync_graphqlEndpoint:
		'https://f27w74iz4vhgvoyq2lnv36smym.appsync-api.us-east-1.amazonaws.com/graphql',
	aws_appsync_region: 'us-east-1',
	aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
}

export default awsmobile

